version: "3.8"

services:
  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    container_name: blog-mongo
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    container_name: blog-redis

  app:
    build: .
    container_name: blog-app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379


volumes:
  mongo_data:
